services:
  kali:
    build:
      context: .
    volumes:
      - sf_vbox:/media/sf_vbox
      # - $GDRIVE/dev/projects/purple-halo:/media/local
    tty: true
    stdin_open: true
    restart: no # 
    command: /bin/bash

volumes:
  sf_vbox:  # This empty declaration is still required for named volumes
  # purple-halo: # Not needed as it is mounted from the host
    